services:
  express:
    env_file: ".env"
    image: ghcr.io/winlost/express-webhook:main
    pull_policy: always
    build: .
    ports:
      - "3001:3001"
    restart: always
    logging:
      driver: syslog
